server:
  port: ${PORT:8080}

spring:
  application:
    name: nord-tool-backend

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
