SPS.CARGO.LISTAR=\
SELECT c.id_cargo AS id, c.nm_cargo AS nmCargo \
FROM cargos c \
ORDER BY c.nm_cargo ASC

SPI.CARGO.INSERIR=\
INSERT INTO cargos (nm_cargo) VALUES (:nmCargo)

SPU.CARGO.ALTERAR=\
UPDATE cargos SET nm_cargo = :nmCargo WHERE id_cargo = :id

SPD.CARGO.DELETAR=\
DELETE FROM cargos WHERE id_cargo = :id
