SPI.COLABORADOR.INSERIR=\
INSERT INTO users (nm_user, nm_celular, id_empresa, id_cargo, id_permissao) \
VALUES (:nmColaborador, :nrCelular, :idEmpresa, :idCargo, :idPermissao)

SPU.COLABORADOR.ALTERAR=\
UPDATE users SET \
    nm_user = :nmColaborador, \
    nm_celular = :nrCelular, \
    id_empresa = :idEmpresa, \
    id_cargo = :idCargo, \
    id_permissao = :idPermissao \
WHERE id_user = :id

SPD.COLABORADOR.DELETAR=\
DELETE FROM users WHERE id_user = :id

SPS.COLABORADOR.LISTAR=\
SELECT \
    u.id_user AS id, \
    u.nm_user AS nmColaborador, \
    u.nm_celular AS nrCelular, \
    u.id_empresa AS idEmpresa, \
    e.nm_empresa AS nmEmpresa, \
    u.id_cargo AS idCargo, \
    c.nm_cargo AS nmCargo, \
    u.id_permissao AS idPermissao, \
    p.nm_permissao AS nmPermissao \
FROM users u \
INNER JOIN empresas e ON e.id_empresa = u.id_empresa \
INNER JOIN cargos c ON c.id_cargo = u.id_cargo \
INNER JOIN permissoes p ON p.id_permissao = u.id_permissao \
ORDER BY u.id_user

SPS.COLABORADOR.BUSCAR_POR_ID=\
SELECT \
    u.id_user AS id, \
    u.nm_user AS nmColaborador, \
    u.nm_celular AS nrCelular, \
    u.id_empresa AS idEmpresa, \
    e.nm_empresa AS nmEmpresa, \
    u.id_cargo AS idCargo, \
    c.nm_cargo AS nmCargo, \
    u.id_permissao AS idPermissao, \
    p.nm_permissao AS nmPermissao \
FROM users u \
INNER JOIN empresas e ON e.id_empresa = u.id_empresa \
INNER JOIN cargos c ON c.id_cargo = u.id_cargo \
INNER JOIN permissoes p ON p.id_permissao = u.id_permissao \
WHERE u.id_user = :id
