SPI.CRONOGRAMA_SEMANAL.INSERIR=\
INSERT INTO cronograma_semanal ( \
    id_dia_semana, \
    nm_cronograma_semanal, \
    nm_horario, \
    nm_categoria, \
    nm_status_cronograma, \
    tx_observacao, \
    dt_prazo, \
    dt_finalizacao, \
    nm_tag, \
    dt_agendamento, \
    fl_fixo \
    ) VALUES ( \
    :idDiaSemana, \
    :nmCronogramaSemanal, \
    :nmHorario, \
    :nmCategoria, \
    :nmStatusCronograma, \
    :txObservacao, \
    :dtPrazo, \
    :dtFinalizacao, \
    :nmTag, \
    :dtAgendamento, \
    :flFixo \
)

SPU.CRONOGRAMA_SEMANAL.ALTERAR=\
UPDATE cronograma_semanal \
SET \
    id_dia_semana        = :idDiaSemana, \
    nm_cronograma_semanal = :nmCronogramaSemanal, \
    nm_horario           = :nmHorario, \
    nm_categoria         = :nmCategoria, \
    nm_status_cronograma = :nmStatusCronograma, \
    tx_observacao        = :txObservacao, \
    dt_prazo             = :dtPrazo, \
    dt_finalizacao       = :dtFinalizacao, \
    nm_tag               = :nmTag, \
    dt_agendamento       = :dtAgendamento, \
    fl_fixo              = :flFixo, \
    dt_alteracao         = NOW() \
WHERE id_cronograma_semanal = :id

SPD.CRONOGRAMA_SEMANAL.DELETAR=\
DELETE FROM cronograma_semanal WHERE id_cronograma_semanal = :id

SPS.CRONOGRAMA_SEMANAL.LISTAR=\
SELECT \
    cs.id_cronograma_semanal AS id, \
    cs.id_dia_semana AS idDiaSemana, \
    ds.nm_dia_semana AS nmDiaSemana, \
    cs.nm_cronograma_semanal AS nmCronogramaSemanal, \
    cs.nm_horario AS nmHorario, \
    cs.nm_categoria AS nmCategoria, \
    cs.nm_status_cronograma AS nmStatusCronograma, \
    cs.tx_observacao AS txObservacao, \
    cs.dt_prazo AS dtPrazo, \
    cs.dt_finalizacao AS dtFinalizacao, \
    cs.nm_tag AS nmTag, \
    cs.dt_agendamento AS dtAgendamento, \
    cs.fl_fixo AS flFixo, \
    cs.nm_usuario nmUsuario, \
    cs.dt_inclusao AS dtInclusao, \
    cs.dt_alteracao AS dtAlteracao \
FROM cronograma_semanal cs \
LEFT JOIN dia_semana ds ON cs.id_dia_semana = ds.id_dia_semana

SPS.CRONOGRAMA_SEMANAL.BUSTAR_POR_ID=\
SELECT \
    cs.id_cronograma_semanal AS id, \
    cs.id_dia_semana AS idDiaSemana, \
    ds.nm_dia_semana AS nmDiaSemana, \
    cs.nm_cronograma_semanal AS nmCronogramaSemanal, \
    cs.nm_horario AS nmHorario, \
    cs.nm_categoria AS nmCategoria, \
    cs.nm_status_cronograma AS nmStatusCronograma, \
    cs.tx_observacao AS txObservacao, \
    cs.dt_prazo AS dtPrazo, \
    cs.dt_finalizacao AS dtFinalizacao, \
    cs.nm_tag AS nmTag, \
    cs.dt_agendamento AS dtAgendamento, \
    cs.fl_fixo AS flFixo, \
    cs.nm_usuario nmUsuario, \
    cs.dt_inclusao AS dtInclusao, \
    cs.dt_alteracao AS dtAlteracao \
FROM cronograma_semanal cs \
LEFT JOIN dia_semana ds ON cs.id_dia_semana = ds.id_dia_semana \
WHERE id_cronograma_semanal = :id
