SPS.EMPRESA.LISTAR=\
SELECT e.id_empresa AS id, e.nm_empresa AS nmEmpresa \
FROM empresas e \
ORDER BY e.nm_empresa ASC

SPI.EMPRESA.INSERIR=\
INSERT INTO empresas (nm_empresa) VALUES (:nmEmpresa)

SPU.EMPRESA.ALTERAR=\
UPDATE empresas SET nm_empresa = :nmEmpresa WHERE id_empresa = :id

SPD.EMPRESA.DELETAR=\
DELETE FROM empresas WHERE id_empresa = :id
