SPI.FERRAMENTA.INSERIR=\
INSERT INTO ferramentas (nm_ferramenta, nm_categoria, cd_patrimonio, fl_ativo) \
VALUES (:nmFerramenta, :nmCategoria, :cdPatrimonio, :flAtivo)

SPU.FERRAMENTA.ALTERAR=\
UPDATE ferramentas SET \
    nm_ferramenta = :nmFerramenta, \
    nm_categoria = :nmCategoria, \
    cd_patrimonio = :cdPatrimonio, \
    fl_ativo = :flAtivo, \
    dt_alteracao = NOW() \
WHERE id_ferramenta = :id

SPD.FERRAMENTA.DELETAR=\
DELETE FROM ferramentas WHERE id_ferramenta = :id

SPS.FERRAMENTA.LISTAR=\
SELECT \
    id_ferramenta AS id, \
    nm_ferramenta AS nmFerramenta, \
    nm_categoria AS nmCategoria, \
    cd_patrimonio AS cdPatrimonio, \
    fl_ativo AS flAtivo \
FROM ferramentas \
ORDER BY nm_ferramenta

SPS.FERRAMENTA.BUSCAR_POR_ID=\
SELECT \
    id_ferramenta AS id, \
    nm_ferramenta AS nmFerramenta, \
    nm_categoria AS nmCategoria, \
    cd_patrimonio AS cdPatrimonio, \
    fl_ativo AS flAtivo \
FROM ferramentas \
WHERE id_ferramenta = :id
