SPI.FERRAMENTA.INSERIR=\
INSERT INTO ferramentas (nm_ferramenta, nm_ferramenta_categoria, cd_ferramenta_patrimonio, in_ferramenta_ativo) \
VALUES (:nmFerramenta, :nmFerramentaCategoria, :cdFerramentaPatrimonio, :inFerramentaAtivo)

SPU.FERRAMENTA.ALTERAR=\
UPDATE ferramentas SET \
    nm_ferramenta = :nmFerramenta, \
    nm_ferramenta_categoria = :nmFerramentaCategoria, \
    cd_ferramenta_patrimonio = :cdFerramentaPatrimonio, \
    in_ferramenta_ativo = :inFerramentaAtivo, \
    dt_alteracao = NOW() \
WHERE id_ferramenta = :id

SPD.FERRAMENTA.DELETAR=\
DELETE FROM ferramentas WHERE id_ferramenta = :id

SPS.FERRAMENTA.LISTAR=\
SELECT \
    id_ferramenta AS id, \
    nm_ferramenta AS nmFerramenta, \
    nm_ferramenta_categoria AS nmFerramentaCategoria, \
    cd_ferramenta_patrimonio AS cdFerramentaPatrimonio, \
    in_ferramenta_ativo AS inFerramentaAtivo \
FROM ferramentas \
ORDER BY nm_ferramenta

SPS.FERRAMENTA.BUSCAR_POR_ID=\
SELECT \
    id_ferramenta AS id, \
    nm_ferramenta AS nmFerramenta, \
    nm_ferramenta_categoria AS nmFerramentaCategoria, \
    cd_ferramenta_patrimonio AS cdFerramentaPatrimonio, \
    in_ferramenta_ativo AS inFerramentaAtivo \
FROM ferramentas \
WHERE id_ferramenta = :id
