SPS.PERMISSAO.LISTAR=\
SELECT p.id_permissao AS id, p.nm_permissao AS nmPermissao \
FROM permissoes p \
ORDER BY p.nm_permissao ASC

SPI.PERMISSAO.INSERIR=\
INSERT INTO permissoes (nm_permissao) VALUES (:nmPermissao)

SPU.PERMISSAO.ALTERAR=\
UPDATE permissoes SET nm_permissao = :nmPermissao WHERE id_permissao = :id

SPD.PERMISSAO.DELETAR=\
DELETE FROM permissoes WHERE id_permissao = :id
